
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 16;
  public static final int OR = 17;
  public static final int CM = 7;
  public static final int THEN = 15;
  public static final int START_S = 10;
  public static final int RO = 19;
  public static final int S = 6;
  public static final int NOT = 18;
  public static final int FI = 14;
  public static final int N = 24;
  public static final int IF = 13;
  public static final int END_S = 11;
  public static final int RC = 20;
  public static final int EOF = 0;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int PRINT = 23;
  public static final int DOT = 22;
  public static final int error = 1;
  public static final int UINT = 9;
  public static final int QSTRING = 8;
  public static final int EQEQ = 21;
  public static final int UMINUS = 25;
  public static final int HOUSE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "CM",
  "QSTRING",
  "UINT",
  "START_S",
  "END_S",
  "HOUSE",
  "IF",
  "FI",
  "THEN",
  "AND",
  "OR",
  "NOT",
  "RO",
  "RC",
  "EQEQ",
  "DOT",
  "PRINT",
  "N",
  "UMINUS"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[16]=new String("AND");
		TT[17]=new String("OR");
		TT[7]=new String("CM");
		TT[15]=new String("THEN");
		TT[10]=new String("START_S");
		TT[19]=new String("RO");
		TT[6]=new String("S");
		TT[18]=new String("NOT");
		TT[14]=new String("FI");
		TT[24]=new String("N");
		TT[13]=new String("IF");
		TT[11]=new String("END_S");
		TT[20]=new String("RC");
		TT[0]=new String("EOF");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[23]=new String("PRINT");
		TT[22]=new String("DOT");
		TT[1]=new String("error");
		TT[9]=new String("UINT");
		TT[8]=new String("QSTRING");
		TT[21]=new String("EQEQ");
		TT[25]=new String("UMINUS");
		TT[12]=new String("HOUSE");
	}
public String getTT(int i){return TT[i];}
}

