
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 2;
  public static final int QSTRING = 34;
  public static final int PRW = 12;
  public static final int UINT = 35;
  public static final int UMINUS = 31;
  public static final int S = 6;
  public static final int COMPW = 14;
  public static final int CW = 13;
  public static final int MINUS = 28;
  public static final int IW = 18;
  public static final int STAR = 29;
  public static final int SINT = 36;
  public static final int LW = 21;
  public static final int TOK3 = 5;
  public static final int CM = 7;
  public static final int TOK2 = 4;
  public static final int TOK1 = 3;
  public static final int DONEW = 20;
  public static final int DIV = 30;
  public static final int RO = 32;
  public static final int PLUS = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RC = 33;
  public static final int BW = 10;
  public static final int ANDW = 24;
  public static final int HW = 22;
  public static final int REAL = 37;
  public static final int COL = 8;
  public static final int BETW = 23;
  public static final int AW = 26;
  public static final int DW = 19;
  public static final int PZ = 17;
  public static final int MW = 25;
  public static final int PY = 16;
  public static final int PX = 15;
  public static final int PW = 11;
  public static final int SW = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "CM",
  "COL",
  "SW",
  "BW",
  "PW",
  "PRW",
  "CW",
  "COMPW",
  "PX",
  "PY",
  "PZ",
  "IW",
  "DW",
  "DONEW",
  "LW",
  "HW",
  "BETW",
  "ANDW",
  "MW",
  "AW",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "UMINUS",
  "RO",
  "RC",
  "QSTRING",
  "UINT",
  "SINT",
  "REAL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[2]=new String("SEP");
		TT[34]=new String("QSTRING");
		TT[12]=new String("PRW");
		TT[35]=new String("UINT");
		TT[31]=new String("UMINUS");
		TT[6]=new String("S");
		TT[14]=new String("COMPW");
		TT[13]=new String("CW");
		TT[28]=new String("MINUS");
		TT[18]=new String("IW");
		TT[29]=new String("STAR");
		TT[36]=new String("SINT");
		TT[21]=new String("LW");
		TT[5]=new String("TOK3");
		TT[7]=new String("CM");
		TT[4]=new String("TOK2");
		TT[3]=new String("TOK1");
		TT[20]=new String("DONEW");
		TT[30]=new String("DIV");
		TT[32]=new String("RO");
		TT[27]=new String("PLUS");
		TT[0]=new String("EOF");
		TT[1]=new String("error");
		TT[33]=new String("RC");
		TT[10]=new String("BW");
		TT[24]=new String("ANDW");
		TT[22]=new String("HW");
		TT[37]=new String("REAL");
		TT[8]=new String("COL");
		TT[23]=new String("BETW");
		TT[26]=new String("AW");
		TT[19]=new String("DW");
		TT[17]=new String("PZ");
		TT[25]=new String("MW");
		TT[16]=new String("PY");
		TT[15]=new String("PX");
		TT[11]=new String("PW");
		TT[9]=new String("SW");
	}
public String getTT(int i){return TT[i];}
}

