
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LS = 13;
  public static final int MAJ = 2;
  public static final int DATE = 12;
  public static final int COMM = 5;
  public static final int AV = 16;
  public static final int LI = 14;
  public static final int COL = 7;
  public static final int N = 10;
  public static final int LETTER = 11;
  public static final int APICSNAME = 9;
  public static final int SO = 17;
  public static final int PERC = 4;
  public static final int EOF = 0;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int SEM = 6;
  public static final int BO = 15;
  public static final int ISBN_code = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAJ",
  "MINUS",
  "PERC",
  "COMM",
  "SEM",
  "COL",
  "ISBN_code",
  "APICSNAME",
  "N",
  "LETTER",
  "DATE",
  "LS",
  "LI",
  "BO",
  "AV",
  "SO"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[13]=new String("LS");
		TT[2]=new String("MAJ");
		TT[12]=new String("DATE");
		TT[5]=new String("COMM");
		TT[16]=new String("AV");
		TT[14]=new String("LI");
		TT[7]=new String("COL");
		TT[10]=new String("N");
		TT[11]=new String("LETTER");
		TT[9]=new String("APICSNAME");
		TT[17]=new String("SO");
		TT[4]=new String("PERC");
		TT[0]=new String("EOF");
		TT[3]=new String("MINUS");
		TT[1]=new String("error");
		TT[6]=new String("SEM");
		TT[15]=new String("BO");
		TT[8]=new String("ISBN_code");
	}
public String getTT(int i){return TT[i];}
}

