
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 14;
  public static final int OR = 15;
  public static final int CM = 7;
  public static final int T = 20;
  public static final int RO = 18;
  public static final int S = 6;
  public static final int NOT = 16;
  public static final int PRICE = 28;
  public static final int VARIABLE = 25;
  public static final int COL = 8;
  public static final int PW = 12;
  public static final int RC = 19;
  public static final int F = 21;
  public static final int SO = 22;
  public static final int EOF = 0;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int WW = 11;
  public static final int EQ = 9;
  public static final int UINT = 26;
  public static final int QSTRING = 24;
  public static final int SC = 23;
  public static final int REAL = 27;
  public static final int CMPW = 10;
  public static final int FW = 13;
  public static final int UMINUS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "CM",
  "COL",
  "EQ",
  "CMPW",
  "WW",
  "PW",
  "FW",
  "AND",
  "OR",
  "NOT",
  "UMINUS",
  "RO",
  "RC",
  "T",
  "F",
  "SO",
  "SC",
  "QSTRING",
  "VARIABLE",
  "UINT",
  "REAL",
  "PRICE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[14]=new String("AND");
		TT[15]=new String("OR");
		TT[7]=new String("CM");
		TT[20]=new String("T");
		TT[18]=new String("RO");
		TT[6]=new String("S");
		TT[16]=new String("NOT");
		TT[28]=new String("PRICE");
		TT[25]=new String("VARIABLE");
		TT[8]=new String("COL");
		TT[12]=new String("PW");
		TT[19]=new String("RC");
		TT[21]=new String("F");
		TT[22]=new String("SO");
		TT[0]=new String("EOF");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[1]=new String("error");
		TT[11]=new String("WW");
		TT[9]=new String("EQ");
		TT[26]=new String("UINT");
		TT[24]=new String("QSTRING");
		TT[23]=new String("SC");
		TT[27]=new String("REAL");
		TT[10]=new String("CMPW");
		TT[13]=new String("FW");
		TT[17]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}

