.model small
.stack

.data                   
 M db  'R','B','C','O','C','F','G','H','K','L','P','M','A','R','A'
 COUNTER  DB 0 
 REM DB  0 
 N DW  4
.startup

 MOV AX,0
 MOV SI,0
  
 LOOP1:  
 MOV BX,0
 MOV BL,M[SI]  ; LOAD EACH ELEMENT OF MATRIX
 CMP BL,'A'   ; CHECK IS EQUAL TO A GO TO FOUND TO CHECK OCCURNESS
 JE  FOUND
NEXT:             ;SET SI FOR NEXT LOAD
 INC SI
 CMP SI,15
 JE  ENDPR
 JMP LOOP1
 
FOUND: INC COUNTER    ;COUNTER OF 'A' ++       
       MOV AX,SI      ;ALWAYS COMPUTE REMAINDER  SI/4 
       MOV DX,0
       DIV N; SI/4
       CMP COUNTER,2   ;CHECK IF IT WAS SECOND OCCURNESS OF 'A'
       JE CHECK
       MOV REM,AL  ; IF IT WAS FIRST TIME SAVE REMAINDER SI/4 IN REM FOR NEXT TIME
       JMP NEXT     ; JMP TO SET NEXT ITERATION OF LOADING MATRIX
 
CHECK:   ;HERE IS WE KNOW IT IS SECOND TIME AND WE HAVE REMAINDER OF SI/4 IN AH
         CMP AL,REM     ; IF REM FIRST TIME AND SECOND TIME IS EQUAL THEN RESULT IS 1 OTHERWISZE 0
         JE RESULT 
         MOV AL,0
         JMP ENDPR 
RESULT:  MOV AL,1         
ENDPR:

.exit

end