
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 8;
  public static final int FP = 9;
  public static final int QMARK = 6;
  public static final int CL = 4;
  public static final int VARIABLE = 2;
  public static final int EOF = 0;
  public static final int ATOM = 3;
  public static final int BP = 10;
  public static final int ID = 12;
  public static final int DOT = 5;
  public static final int error = 1;
  public static final int COM = 7;
  public static final int SM = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VARIABLE",
  "ATOM",
  "CL",
  "DOT",
  "QMARK",
  "COM",
  "MINUS",
  "FP",
  "BP",
  "SM",
  "ID"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("MINUS");
		TT[9]=new String("FP");
		TT[6]=new String("QMARK");
		TT[4]=new String("CL");
		TT[2]=new String("VARIABLE");
		TT[0]=new String("EOF");
		TT[3]=new String("ATOM");
		TT[10]=new String("BP");
		TT[12]=new String("ID");
		TT[5]=new String("DOT");
		TT[1]=new String("error");
		TT[7]=new String("COM");
		TT[11]=new String("SM");
	}
public String getTT(int i){return TT[i];}
}

