
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CM = 7;
  public static final int S = 6;
  public static final int PRICE = 17;
  public static final int COL = 8;
  public static final int SO = 9;
  public static final int EOF = 0;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int KW = 12;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int DOT = 13;
  public static final int UINT = 15;
  public static final int KGW = 11;
  public static final int QSTRING = 14;
  public static final int SC = 10;
  public static final int REAL = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "CM",
  "COL",
  "SO",
  "SC",
  "KGW",
  "KW",
  "DOT",
  "QSTRING",
  "UINT",
  "REAL",
  "PRICE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[7]=new String("CM");
		TT[6]=new String("S");
		TT[17]=new String("PRICE");
		TT[8]=new String("COL");
		TT[9]=new String("SO");
		TT[0]=new String("EOF");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[12]=new String("KW");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[1]=new String("error");
		TT[13]=new String("DOT");
		TT[15]=new String("UINT");
		TT[11]=new String("KGW");
		TT[14]=new String("QSTRING");
		TT[10]=new String("SC");
		TT[16]=new String("REAL");
	}
public String getTT(int i){return TT[i];}
}

