
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 21;
  public static final int CM = 7;
  public static final int S = 6;
  public static final int PRICE = 13;
  public static final int FUEL = 18;
  public static final int COL = 8;
  public static final int VARIABLE = 10;
  public static final int SINT = 14;
  public static final int EOF = 0;
  public static final int POSITION = 17;
  public static final int SET = 16;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int EQ = 22;
  public static final int BO = 20;
  public static final int UINT = 11;
  public static final int QSTRING = 9;
  public static final int REAL = 12;
  public static final int DECLARE = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "CM",
  "COL",
  "QSTRING",
  "VARIABLE",
  "UINT",
  "REAL",
  "PRICE",
  "SINT",
  "MINUS",
  "SET",
  "POSITION",
  "FUEL",
  "DECLARE",
  "BO",
  "BC",
  "EQ"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[21]=new String("BC");
		TT[7]=new String("CM");
		TT[6]=new String("S");
		TT[13]=new String("PRICE");
		TT[18]=new String("FUEL");
		TT[8]=new String("COL");
		TT[10]=new String("VARIABLE");
		TT[14]=new String("SINT");
		TT[0]=new String("EOF");
		TT[17]=new String("POSITION");
		TT[16]=new String("SET");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[15]=new String("MINUS");
		TT[1]=new String("error");
		TT[22]=new String("EQ");
		TT[20]=new String("BO");
		TT[11]=new String("UINT");
		TT[9]=new String("QSTRING");
		TT[12]=new String("REAL");
		TT[19]=new String("DECLARE");
	}
public String getTT(int i){return TT[i];}
}

