
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 8;
  public static final int OR = 9;
  public static final int WORDS = 17;
  public static final int T = 18;
  public static final int EMAIL = 27;
  public static final int S = 6;
  public static final int RO = 12;
  public static final int NOT = 10;
  public static final int VARIABLE = 14;
  public static final int WITH = 20;
  public static final int LOWERCASE = 16;
  public static final int RC = 13;
  public static final int F = 19;
  public static final int SO = 22;
  public static final int EOF = 0;
  public static final int CMP = 7;
  public static final int DIV = 26;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int EQ = 25;
  public static final int UPPERCASE = 15;
  public static final int QSTRING = 24;
  public static final int SC = 23;
  public static final int UMINUS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "CMP",
  "AND",
  "OR",
  "NOT",
  "UMINUS",
  "RO",
  "RC",
  "VARIABLE",
  "UPPERCASE",
  "LOWERCASE",
  "WORDS",
  "T",
  "F",
  "WITH",
  "PRINT",
  "SO",
  "SC",
  "QSTRING",
  "EQ",
  "DIV",
  "EMAIL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("AND");
		TT[9]=new String("OR");
		TT[17]=new String("WORDS");
		TT[18]=new String("T");
		TT[27]=new String("EMAIL");
		TT[6]=new String("S");
		TT[12]=new String("RO");
		TT[10]=new String("NOT");
		TT[14]=new String("VARIABLE");
		TT[20]=new String("WITH");
		TT[16]=new String("LOWERCASE");
		TT[13]=new String("RC");
		TT[19]=new String("F");
		TT[22]=new String("SO");
		TT[0]=new String("EOF");
		TT[7]=new String("CMP");
		TT[26]=new String("DIV");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[21]=new String("PRINT");
		TT[1]=new String("error");
		TT[25]=new String("EQ");
		TT[15]=new String("UPPERCASE");
		TT[24]=new String("QSTRING");
		TT[23]=new String("SC");
		TT[11]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}

